# Generated by Django 5.1.6 on 2025-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عناون الخبر')),
                ('date', models.DateField(verbose_name='تاريخ الخبر')),
                ('details', models.TextField(verbose_name='التفاصيل')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_images/', verbose_name='صورة')),
            ],
        ),
    ]
