# Generated by Django 5.1.6 on 2025-02-15 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم')),
                ('job_title', models.CharField(max_length=100, verbose_name='الوظيفة الحالية')),
                ('birth_year', models.IntegerField(verbose_name='تاريخ الولادة')),
                ('bio', models.TextField(verbose_name='السيرة الذاتية')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_images/', verbose_name='الصورة')),
            ],
        ),
    ]
